# Generated by Django 4.2.1 on 2025-11-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechareg', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_tramite', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('REVISION', 'En revisión'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita_presencial', models.DateTimeField(blank=True, null=True)),
                ('asistio_cita', models.BooleanField(default=False)),
                ('status', models.BooleanField()),
                ('contribuyent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.contribuyente')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='tram_planillas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_planilla', models.CharField(blank=True, max_length=35, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'tram_planillas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='tram_solv_veh',
            fields=[
                ('idvehi', models.AutoField(primary_key=True, serialize=False)),
                ('n_placa', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('num_estampilla', models.CharField(max_length=30)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_vehiculo/')),
                ('codigo_planilla', models.CharField(max_length=20)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_vehiculo/')),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitud_vehi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_solv_veh', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_solv_veh',
                'ordering': ['-idvehi'],
            },
        ),
        migrations.CreateModel(
            name='tram_solv_pub',
            fields=[
                ('idpubli', models.AutoField(primary_key=True, serialize=False)),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField(null=True)),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_public/')),
                ('cod_planilla', models.CharField(max_length=20, unique=True)),
                ('planilla_solicitud', models.FileField(blank=True, null=True, upload_to='imagenPublicidad/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitud_publi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_solv_pub', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_solv_pub',
                'ordering': ['-idpubli'],
            },
        ),
        migrations.CreateModel(
            name='tram_solv_inm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_inm/')),
                ('codigo_cast', models.CharField(blank=True, max_length=20, unique=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=20, unique=True)),
                ('codigo_planilla', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_inm/')),
                ('otros', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.CharField(choices=[('registro', 'Registro'), ('construcion', 'Construcción'), ('regist_hipo', 'Registro de Hipoteca'), ('posesion', 'Posesión'), ('remate', 'Remate'), ('solicit_arrend', 'Solicitud de Arriendamiento'), ('mensura', 'Mensura'), ('desocupacion', 'Desocupación'), ('internas', 'Internas'), ('tribut_espec', 'Tributaria Especial'), ('rural', 'Rural'), ('inti', 'INTI'), ('otros', 'otros')], default='registro', max_length=40)),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_planillas')),
                ('solicitud_inmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_solv_inm', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_solv_inm',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='tram_solv_actecon',
            fields=[
                ('idact', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_planilla', models.CharField(max_length=20)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_actecono/')),
                ('num_estampilla', models.CharField(max_length=30)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_actecono/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_solv_actecon', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_solv_actecon',
                'ordering': ['-idact'],
            },
        ),
        migrations.CreateModel(
            name='tram_ivss_reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_ivss_reg/')),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_ivss_reg/')),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitud_ivssreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_ivss_reg', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_ivss_reg',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='tram_ivss_noreg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_ivss_noreg/')),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_ivss_noreg/')),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitud_ivssnoreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_ivss_noreg', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_ivss_noreg',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='tram_const_exen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sap', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('codigo_planilla', models.CharField(max_length=20)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_const_exen/')),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_const_exen/')),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitudexen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_const_exen', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_const_exen',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='tram_cese_temp',
            fields=[
                ('idCe_temp', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_cese_temp/')),
                ('codigo_planilla', models.CharField(max_length=20)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_cese_temp/')),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitudCesetemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_cese_temp', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_cese_temp',
                'ordering': ['-idCe_temp'],
            },
        ),
        migrations.CreateModel(
            name='tram_cese_def',
            fields=[
                ('idCe_def', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('n_estampilla', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_estampilla', models.DateField()),
                ('Imagen_estampilla', models.FileField(blank=True, upload_to='Estampilla_cese_def/')),
                ('codigo_planilla', models.CharField(max_length=20, unique=True)),
                ('planilla_solicitud', models.FileField(blank=True, upload_to='planilla_cese_def/')),
                ('num_pago', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField()),
                ('solicitudCesedefi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tram_cese_def', to='tramites.solicitudtramite')),
            ],
            options={
                'db_table': 'tram_cese_def',
                'ordering': ['-idCe_def'],
            },
        ),
        migrations.CreateModel(
            name='pagos_pendientes_cesesdefitemp',
            fields=[
                ('idpagocesedeftemp', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCese', models.CharField(choices=[('Cese_definitiva', 'Cese definitiva'), ('Cese_temporal', 'Cese_temporal')], default='Cese_temporal', max_length=40)),
                ('monto_total_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
                ('num_tram_cese_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pendientes_cesesdef', to='tramites.tram_cese_def')),
                ('num_tram_cese_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pendientes_cesesdef', to='tramites.tram_cese_temp')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('area_destino', models.CharField(max_length=100)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tramites.solicitudtramite')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramites.contribuyente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='detalles_pagos_cesesdeftemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=255)),
                ('periodo_fiscal', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
                ('idpagocesedeftemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pagos', to='tramites.pagos_pendientes_cesesdefitemp')),
            ],
        ),
    ]
