# Generated by Django 4.2.1 on 2025-11-18 16:54

import act_econ.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=15, unique=True)),
                ('carpeta', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('documento', models.CharField(max_length=15)),
                ('razon_social', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('contribuyentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.contribuyente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_actecon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ae_empresas',
                'ordering': ['-licencia'],
            },
        ),
        migrations.CreateModel(
            name='Empresas_licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_Merca', models.FileField(blank=True, null=True, upload_to=act_econ.models.carpeta_empresa_upload_to)),
                ('rif', models.FileField(blank=True, null=True, upload_to=act_econ.models.carpeta_empresa_upload_to)),
                ('cedula_repre', models.FileField(blank=True, null=True, upload_to=act_econ.models.carpeta_empresa_upload_to)),
                ('licenciaE', models.FileField(blank=True, null=True, upload_to=act_econ.models.carpeta_empresa_upload_to)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act_econ.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Act_econ_Solvencia',
            fields=[
                ('idSolv', models.AutoField(primary_key=True, serialize=False)),
                ('n_control', models.CharField(blank=True, max_length=50, unique=True)),
                ('contribuyente', models.CharField(blank=True, max_length=150)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('direcc', models.CharField(blank=True, max_length=150)),
                ('n_planilla', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=120)),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvencias_actecon', to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='act_econ.empresas')),
                ('solicitud_solv', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_solv_actecon')),
            ],
            options={
                'db_table': 'ae_solvencia',
                'ordering': ['-n_control'],
            },
        ),
        migrations.CreateModel(
            name='Act_econ_no_contribuyente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_control', models.CharField(blank=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('cedula', models.CharField(max_length=20)),
                ('n_planilla', models.CharField(max_length=50)),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_contribuyentes_actecon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ae_no_contribuyente',
                'ordering': ['-n_control'],
            },
        ),
        migrations.CreateModel(
            name='Act_econ_ivss_noreg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_control', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=30)),
                ('empresas', models.CharField(max_length=250)),
                ('planilla', models.CharField(max_length=50)),
                ('fecha_plan', models.DateField(null=True)),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivss_noreg_actecon', to=settings.AUTH_USER_MODEL)),
                ('num_solicitud_ivssAct', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_ivss_noreg')),
            ],
            options={
                'db_table': 'ae_conts_ivss_nrg',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Act_econ_ivss_act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_control', models.CharField(blank=True, max_length=50, null=True)),
                ('rif', models.CharField(blank=True, max_length=30)),
                ('nomb_empresa', models.CharField(blank=True, max_length=250)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=30)),
                ('planilla', models.CharField(max_length=50)),
                ('fecha_plan', models.DateField(null=True)),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivss_actecon', to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='act_econ.empresas')),
                ('num_solicitud_ivssAct', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_ivss_reg')),
            ],
            options={
                'db_table': 'ae_conts_ivss_act',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Act_econ_constancia',
            fields=[
                ('idc', models.AutoField(primary_key=True, serialize=False)),
                ('n_control_const', models.CharField(blank=True, max_length=50, unique=True)),
                ('nomb_empresa', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('planilla', models.CharField(max_length=50)),
                ('fecha_plan', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constancias_actecon', to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='act_econ.empresas')),
            ],
            options={
                'db_table': 'ae_constancia',
                'ordering': ['-idc'],
            },
        ),
    ]
