# Generated by Django 4.2.1 on 2025-11-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inmueble_urb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles_all',
            fields=[
                ('id_inmu', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sap', models.CharField(max_length=15, unique=True)),
                ('codigo_cast', models.CharField(blank=True, max_length=50, unique=True)),
                ('carpeta', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('nombre_contr', models.CharField(max_length=150, null=True)),
                ('dir_inmueble', models.TextField(blank=True, max_length=250, null=True)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('altitud', models.CharField(max_length=15, null=True)),
                ('latitud', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('contribuye_Inmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.contribuyente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inmuebles_all', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inm_info',
            },
        ),
        migrations.CreateModel(
            name='Inmueble_cod_sap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.FileField(blank=True, null=True, upload_to=inmueble_urb.models.carpeta_inmueble_upload_to)),
                ('avaluo', models.FileField(blank=True, null=True, upload_to=inmueble_urb.models.carpeta_inmueble_upload_to)),
                ('rif', models.FileField(blank=True, null=True, upload_to=inmueble_urb.models.carpeta_inmueble_upload_to)),
                ('contrato', models.FileField(blank=True, null=True, upload_to=inmueble_urb.models.carpeta_inmueble_upload_to)),
                ('escritura', models.FileField(blank=True, null=True, upload_to=inmueble_urb.models.carpeta_inmueble_upload_to)),
                ('boletinCatast', models.FileField(blank=True, upload_to=inmueble_urb.models.carpeta_inmueble_upload_to)),
                ('Inmueble_sap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueble_urb.inmuebles_all')),
            ],
        ),
        migrations.CreateModel(
            name='Inm_Solvencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_control_Inm', models.CharField(max_length=10, unique=True)),
                ('nomb_contribuyente', models.CharField(max_length=200)),
                ('direcc', models.CharField(max_length=120)),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('n_planilla', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('observ_2', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('cod_catas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueble_urb.inmuebles_all')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inm_Solvencia', to=settings.AUTH_USER_MODEL)),
                ('num_tramite_In', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_solv_inm')),
            ],
            options={
                'db_table': 'inm_solvencia',
                'ordering': ['-n_control_Inm'],
            },
        ),
    ]
