# Generated by Django 4.2.1 on 2025-11-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=30)),
                ('Estado_civil', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('hijos', models.IntegerField()),
                ('estatus', models.BooleanField()),
            ],
            options={
                'db_table': 'trabajador',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='trabajador_area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
                ('TipoTrab', models.CharField(choices=[('Empleado', 'Empleado'), ('Contratado', 'Contratado')], default='Empleado', max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('fechaIngreso', models.DateField()),
                ('fechaRetiro', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estatus', models.BooleanField()),
                ('cedulaT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_trabajador_gerente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
                ('fechaCargo', models.DateField()),
                ('resolucion', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('estatus', models.BooleanField()),
                ('cedulaT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.trabajador')),
            ],
        ),
    ]
