# Generated by Django 4.2.1 on 2025-11-18 16:54

import act_econ.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('act_econ', '0001_initial'),
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='publicidad_Solvencia',
            fields=[
                ('idSolv', models.AutoField(primary_key=True, serialize=False)),
                ('n_control', models.CharField(blank=True, max_length=50, unique=True)),
                ('contribuyente', models.CharField(blank=True, max_length=150)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('direcc', models.CharField(blank=True, max_length=150)),
                ('n_planilla', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('fecha_exp', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=120)),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvencias_publicidad', to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='act_econ.empresas')),
                ('solicitud_solv', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_solv_pub')),
            ],
            options={
                'db_table': 'publici_solvencia',
                'ordering': ['-n_control'],
            },
        ),
        migrations.CreateModel(
            name='Empresas_licencia_Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=act_econ.models.carpeta_empresa_upload_to)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act_econ.empresas')),
            ],
        ),
    ]
