# Generated by Django 4.2.1 on 2025-11-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehiculo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Marca_vehi',
                'ordering': ['-idMarca'],
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Modelo_vehi',
                'ordering': ['-idModelo'],
            },
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=30, unique=True)),
                ('carpeta', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('año', models.IntegerField()),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('cedula_func', models.CharField(blank=True, max_length=15)),
                ('nomb_func', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('contribuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.contribuyente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_all', to=settings.AUTH_USER_MODEL)),
                ('marcaVehi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.marcavehiculo')),
                ('modeloVehi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.modelovehiculo')),
            ],
            options={
                'db_table': 'vehiculo',
                'ordering': ['-placa'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculos_placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaV', models.FileField(upload_to=vehiculo.models.carpeta_vehiculo_upload_to)),
                ('Vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='vehi_Solvencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('n_control_Vehi', models.CharField(blank=True, max_length=50, unique=True)),
                ('contribuyente', models.CharField(max_length=200)),
                ('n_planilla', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('observ_2', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehi_Solvencia', to=settings.AUTH_USER_MODEL)),
                ('n_placa_Vehi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculos')),
                ('num_tramite_Veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tram_solv_veh')),
            ],
            options={
                'db_table': 'veh_Solvencia',
                'ordering': ['-n_placa_Vehi'],
            },
        ),
    ]
